version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: tickets_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ekaterinariadcikova
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tickets_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
